### ISSUE TITLE
java.lang.ClassNotFoundException: okio.Source

### ISSUE THREAD

**Issue by iockx** [gateio/gateapi-java#19]
When executing the example, this error may occur, but I couldn't find this dependency package online. Have any friends encountered it

```java
Caused by: java.lang.ClassNotFoundException: okio.Source
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 2 more
```

**Comment by iockx** [comment]
It should be my problem. I will make an error when packaging and importing, but running it in the original project will not make an error
