### ISSUE TITLE
还款失败

### ISSUE THREAD

**Issue by padin** [gateio/gateapi-java#28]
uid:10393504
{"currency":"BSV","type":"repay","amount":"0.0725"}
io.gate.gateapi.api.UnifiedApi#createUnifiedLoan

**Comment by padin** [comment]
2024-12-13T14:58:00.927+08:00  INFO 2962982 --- [   scheduling-1] com.wyizd.trade.api.UnifiedService       : 开始还款{"currency":"ICP","type":"repay","amount":"0.35"}
2024-12-13T14:58:01.052+08:00 ERROR 2962982 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.lang.RuntimeException: io.gate.gateapi.ApiException: , {"label":"SERVER_ERROR","message":"Internal server error"}
Caused by: io.gate.gateapi.ApiException: , {"label":"SERVER_ERROR","message":"Internal server error"}
	at io.gate.gateapi.ApiClient.handleResponse(ApiClient.java:1004) ~[gate-api-6.78.0.jar!/:na]
	at io.gate.gateapi.ApiClient.execute(ApiClient.java:911) ~[gate-api-6.78.0.jar!/:na]
	at io.gate.gateapi.ApiClient.execute(ApiClient.java:894) ~[gate-api-6.78.0.jar!/:na]
	at io.gate.gateapi.api.UnifiedApi.createUnifiedLoanWithHttpInfo(UnifiedApi.java:920) ~[gate-api-6.78.0.jar!/:na]
	at io.gate.gateapi.api.UnifiedApi.createUnifiedLoan(UnifiedApi.java:903) ~[gate-api-6.78.0.jar!/:na]
	at com.wyizd.trade.api.UnifiedService.repay(UnifiedService.java:72) ~[!/:1.0-SNAPSHOT]

**Comment by padin** [comment]
因为是内部服务器错误,不理解什么原因导致,劳烦解答一下

**Comment by revilwang** [comment]
涉及到服务报错问题，可以通过官方客服渠道反馈到对应的业务技术团队去跟踪，这是是 sdk 相关的问题解答
